### PR TITLE
Handle no node pools for hybrid org cluster

### LINKED ISSUE #1691: Panic on deploying to new deployment on hybrid cluster
**Describe the bug**

`astro deploy` is hitting a nil pointer dereference when attempting to read the node pools of the cluster to create a new deployment on.

```
% astro deploy

Current Workspace: test

Please specify a name for your Deployment

Deployment name: test

Please select a Cluster for your Deployment:
 #     CLUSTER NAME     CLOUD PROVIDER     CLUSTER ID
 1     test hosted      AZURE              ***
 2     test             AZURE              ***

> 1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x10313c590]

goroutine 1 [running]:
github.com/astronomer/astro-cli/cloud/deployment.Create({0x0, _}, {_, _}, {_, _}, {_, _}, {_, _}, ...)
        github.com/astronomer/astro-cli/cloud/deployment/deployment.go:442 +0x990
github.com/astronomer/astro-cli/cloud/deployment.deploymentSelectionProcess({_, _}, {_, _, _}, _, {_, _}, {_, _}, ...)
        github.com/astronomer/astro-cli/cloud/deployment/deployment.go:1711 +0x2bc
github.com/astronomer/astro-cli/cloud/deployment.GetDeployment({_, _}, {_, _}, {_, _}, _, _, {_, _}, ...)
        github.com/astronomer/astro-cli/cloud/deployment/deployment.go:1659 +0x1e0
github.com/astronomer/astro-cli/cloud/deploy.getDeploymentInfo({0x0?, 0x140005b5748?}, {0x140000414c0, 0x19}, {0x0, 0x0}, 0x0, {0x103d7d780, 0x1400032bb30}, {_, ...})
        github.com/astronomer/astro-cli/cloud/deploy/deploy.go:422 +0x1c4
github.com/astronomer/astro-cli/cloud/deploy.Deploy({{0x140000440c4, 0x2f}, {0x0, 0x0}, {0x140000414c0, 0x19}, {0x103794544, 0x5}, {0x103793a9d, 0x4}, ...}, ...)
        github.com/astronomer/astro-cli/cloud/deploy/deploy.go:206 +0x2c0
github.com/astronomer/astro-cli/cmd/cloud.deploy(0x14000123508, {0x1047a1440?, 0x4?, 0x103793bed?})
        github.com/astronomer/astro-cli/cmd/cloud/deploy.go:158 +0x50c
github.com/spf13/cobra.(*Command).execute(0x14000123508, {0x1047a1440, 0x0, 0x0})
        github.com/spf13/cobra@v1.7.0/command.go:940 +0x654
github.com/spf13/cobra.(*Command).ExecuteC(0x140001d3508)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(0x103d733a0?)
        github.com/spf13/cobra@v1.7.0/command.go:992 +0x1c
main.main()
        github.com/astronomer/astro-cli/main.go:21 +0x38
```

**What CLI Version did you experience this bug?**

1.28.1

**This CLI bug is related to which Astronomer Platform?**

- [x] Astro
- [ ] Software
- [ ] None/Unknown

**What Operating System is the above CLI installed on?**

**🪜 Steps To Reproduce**

1. Create cluster on hybrid organization
2. Run `astro deploy` on workspace with no deployments, triggering create deployment flow

### PR DESCRIPTION
**Pull request by jeremybeard**
## Description

This change avoids a panic when there are no node pools being returned for a cluster of a hybrid organization when creating/updating a deployment, by falling back to an empty node pool id.

## 🎟 Issue(s)

Fixes #1691 

## 🧪 Functional Testing

- Unit tested

## 📋 Checklist

- [x] Rebased from the main (or release if patching) branch (before testing)
- [x] Ran `make test` before taking out of draft
- [x] Ran `make lint` before taking out of draft
- [x] Added/updated applicable tests
- [ ] Tested against [Astro-API](https://github.com/astronomer/astro/) (if necessary).
- [ ] Tested against [Houston-API](https://github.com/astronomer/houston-api/) and [Astronomer](https://github.com/astronomer/astronomer/) (if necessary).
- [ ] Communicated to/tagged owners of respective clients potentially impacted by these changes.
- [ ] Updated any related [documentation](https://github.com/astronomer/docs/)

### CODE REVIEW

File: cloud/deployment/deployment.go [hunk 1]
```diff
@@ -520,6 +519,13 @@ func Create(name, workspaceID, description, clusterID, runtimeVersion, dagDeploy
 	return nil
 }
 
+func getDefaultNodePoolID(nodePools *[]astroplatformcore.NodePool) string {
```
Comment (neel-astro) [inline cloud/deployment/deployment.go:522]: why do we even use a pointer to an array on the Core side 🤯

**Review by neel-astro — APPROVED** [review]
LGTM, the fix looks in line and the unit tests cover the panic case

File: cloud/deployment/deployment.go (hunk 1 above)
Comment (jeremybeard) [reply cloud/deployment/deployment.go:522]: Ha, we don't, it's just generated like this on the CLI side because the field is optional in the API spec.
